import { environment } from '../../../environments/environment';

const BASE = environment.apiUrl;

export const API_URLS = {
  auth: {
    login: `${BASE}/auth/login`,
    refresh: `${BASE}/auth/refresh`,
    logout: `${BASE}/auth/logout`,
    me: `${BASE}/auth/me`,
    changePassword: `${BASE}/auth/change-password`,
  },
  admin: {
    users: `${BASE}/admin/users`,
    campaigns: `${BASE}/admin/campaigns`,
    countries: `${BASE}/admin/countries`,
    roles: `${BASE}/admin/roles`,
    auditLog: `${BASE}/admin/audit-log`,
    stats: `${BASE}/admin/stats`,
    rechargesDashboard: `${BASE}/admin/recharges-dashboard`,
    conglomeradoEntries: `${BASE}/admin/conglomerado-entries`,
    pautadorAccounts: (id: number) => `${BASE}/admin/users/${id}/google-ads-accounts`,
    allGoogleAdsAccounts: `${BASE}/admin/users/google-ads-accounts`,
  },
  conglomerado: {
    entryToday: `${BASE}/conglomerado/entry/today`,
    entry: `${BASE}/conglomerado/entry`,
    entries: `${BASE}/conglomerado/entries`,
    weeklySummary: `${BASE}/conglomerado/weekly-summary`,
  },
  pautadores: {
    entriesDaily: `${BASE}/pautadores/entries/daily`,
    entriesWeekly: `${BASE}/pautadores/entries/weekly`,
    entriesWeeklyCalendar: `${BASE}/pautadores/entries/weekly-calendar`,
    consolidated: `${BASE}/pautadores/consolidated`,
    campaigns: `${BASE}/pautadores/campaigns`,
    dashboardKpis: `${BASE}/pautadores/dashboard/kpis`,
    dashboardCharts: `${BASE}/pautadores/dashboard/charts`,
    exportExcel: `${BASE}/pautadores/export/excel`,
    exportPdf: `${BASE}/pautadores/export/pdf`,
    conglomeradoContrast: `${BASE}/pautadores/conglomerado-contrast`,
  },
  gestion: {
    dashboardKpis: `${BASE}/gestion/dashboard/kpis`,
    reportsEffectiveness: `${BASE}/gestion/reports/effectiveness`,
    reportsConversions: `${BASE}/gestion/reports/conversions`,
    reportsByCountry: `${BASE}/gestion/reports/by-country`,
    reportsByWeek: `${BASE}/gestion/reports/by-week`,
    exportExcel: `${BASE}/gestion/export/excel`,
    exportPdf: `${BASE}/gestion/export/pdf`,
    rotations: `${BASE}/gestion/rotations`,
    rotationsAvailableUsers: `${BASE}/gestion/rotations/available-users`,
    rotationsCampaigns: `${BASE}/gestion/rotations/campaigns`,
    conglomeradoUsers: `${BASE}/gestion/conglomerado-users`,
    soporteImages: `${BASE}/gestion/soporte-images`,
    resetEntry: (id: number) => `${BASE}/gestion/entries/${id}`,
    resetPassword: (id: number) => `${BASE}/gestion/conglomerado-users/${id}/reset-password`,
    masters: `${BASE}/gestion/masters`,
    masterEvaluations: (masterUserId: number) => `${BASE}/gestion/masters/${masterUserId}/evaluations`,
    deleteEvaluation: (evalId: number) => `${BASE}/gestion/masters/evaluations/${evalId}`,
    gestionUserCountries: (userId: number) => `${BASE}/gestion/gestion-users/${userId}/countries`,
  },
  notifications: {
    list: `${BASE}/notifications`,
    unread: `${BASE}/notifications/unread`,
    markRead: (id: number) => `${BASE}/notifications/${id}/read`,
    markAllRead: `${BASE}/notifications/read-all`,
  },
  campaignReports: {
    list: `${BASE}/campaign-reports`,
    create: `${BASE}/campaign-reports`,
    campaigns: `${BASE}/campaign-reports/campaigns`,
  },
  contabilidad: {
    kpis: `${BASE}/contabilidad/kpis`,
    cierres: `${BASE}/contabilidad/cierres`,
    vouchers: (entryId: number) => `${BASE}/contabilidad/entries/${entryId}/vouchers`,
    reviewVoucher: (voucherId: number) => `${BASE}/contabilidad/vouchers/${voucherId}/review`,
  },
  system: {
    countries: `${BASE}/system/countries`,
    health: `${BASE}/system/health`,
  },
  googleAds: {
    campaigns: `${BASE}/pautadores/google-ads/campaigns`,
    campaignsByAccount: `${BASE}/pautadores/google-ads/campaigns-by-account`,
    campaignHistory: `${BASE}/pautadores/google-ads/campaigns`,
    billingAccounts: `${BASE}/pautadores/google-ads/billing/accounts`,
    billingHistory: `${BASE}/pautadores/google-ads/billing/history`,
    accountCharges: `${BASE}/pautadores/google-ads/billing/charges`,
    recharges: `${BASE}/pautadores/google-ads/billing/recharges`,
    rechargesExport: `${BASE}/pautadores/google-ads/billing/recharges/export`,
    sync: `${BASE}/pautadores/google-ads/sync`,
    syncCampaigns: `${BASE}/pautadores/google-ads/sync-campaigns`,
    analysisSpendingTrend: `${BASE}/pautadores/google-ads/analysis/spending-trend`,
    analysisDataRange: `${BASE}/pautadores/google-ads/analysis/data-range`,
    analysisPerformance: `${BASE}/pautadores/google-ads/analysis/performance`,
    analysisRankings: `${BASE}/pautadores/google-ads/analysis/rankings`,
    analysisBudgetDistribution: `${BASE}/pautadores/google-ads/analysis/budget-distribution`,
    analysisCampaignTypes: `${BASE}/pautadores/google-ads/analysis/campaign-types`,
    analysisBiddingStrategies: `${BASE}/pautadores/google-ads/analysis/bidding-strategies`,
    analysisKeywords: `${BASE}/pautadores/google-ads/analysis/keywords`,
    analysisKeywordQuality: `${BASE}/pautadores/google-ads/analysis/keyword-quality`,
    analysisDevices: `${BASE}/pautadores/google-ads/analysis/devices`,
    analysisHourlyHeatmap: `${BASE}/pautadores/google-ads/analysis/hourly-heatmap`,
    analysisBudgetPacing: `${BASE}/pautadores/google-ads/analysis/budget-pacing`,
    analysisWasteDetection: `${BASE}/pautadores/google-ads/analysis/waste-detection`,
    analysisOptimalSchedule: `${BASE}/pautadores/google-ads/analysis/optimal-schedule`,
    analysisBudgetForecast: `${BASE}/pautadores/google-ads/analysis/budget-forecast`,
    analysisBudgetRedistribution: `${BASE}/pautadores/google-ads/analysis/budget-redistribution`,
    analysisTemporalComparison: `${BASE}/pautadores/google-ads/analysis/temporal-comparison`,
    analysisCPAAnalysis: `${BASE}/pautadores/google-ads/analysis/cpa-analysis`,
    analysisQualityScoreTrend: `${BASE}/pautadores/google-ads/analysis/quality-score-trend`,
    analysisCPCTrend: `${BASE}/pautadores/google-ads/analysis/cpc-trend`,
    analysisSeasonality: `${BASE}/pautadores/google-ads/analysis/seasonality`,
    analysisSearchTerms: `${BASE}/pautadores/google-ads/analysis/search-terms`,
    analysisNegativeKeywordCandidates: `${BASE}/pautadores/google-ads/analysis/negative-keyword-candidates`,
    analysisLongTail: `${BASE}/pautadores/google-ads/analysis/long-tail`,
    analysisKeywordCannibalization: `${BASE}/pautadores/google-ads/analysis/keyword-cannibalization`,
    analysisAdPerformanceComparison: `${BASE}/pautadores/google-ads/analysis/ad-performance-comparison`,
    analysisAdFatigue: `${BASE}/pautadores/google-ads/analysis/ad-fatigue`,
    analysisAdTypePerformance: `${BASE}/pautadores/google-ads/analysis/ad-type-performance`,
    analysisAuctionInsights: `${BASE}/pautadores/google-ads/analysis/auction-insights`,
    analysisCompetitivePosition: `${BASE}/pautadores/google-ads/analysis/competitive-position`,
    analysisMarketOpportunities: `${BASE}/pautadores/google-ads/analysis/market-opportunities`,
    analysisAgeBreakdown: `${BASE}/pautadores/google-ads/analysis/age-breakdown`,
    analysisGenderBreakdown: `${BASE}/pautadores/google-ads/analysis/gender-breakdown`,
    // Phase 9: Enhanced Tabs
    analysisDeviceBidRecommendations: `${BASE}/pautadores/google-ads/analysis/device-bid-recommendations`,
    analysisDeviceExclusions: `${BASE}/pautadores/google-ads/analysis/device-exclusions`,
    analysisKeywordActionPlan: `${BASE}/pautadores/google-ads/analysis/keyword-action-plan`,
    analysisMatchTypeRecommendations: `${BASE}/pautadores/google-ads/analysis/match-type-recommendations`,
    analysisCrossAccountKeywords: `${BASE}/pautadores/google-ads/analysis/cross-account-keywords`,
    analysisFullForecast: `${BASE}/pautadores/google-ads/analysis/full-forecast`,
    analysisScalingHealth: `${BASE}/pautadores/google-ads/analysis/scaling-health`,
    analysisCompetitiveMarketTrend: `${BASE}/pautadores/google-ads/analysis/competitive-market-trend`,
    // Phase 10: Dashboard Ejecutivo
    analysisAccountHealthScores: `${BASE}/pautadores/google-ads/analysis/account-health-scores`,
    analysisExecutiveSummary: `${BASE}/pautadores/google-ads/analysis/executive-summary`,
    analysisTopRecommendations: `${BASE}/pautadores/google-ads/analysis/top-recommendations`,
    // Phase 11: Auditoria Financiera
    analysisZombieKeywords: `${BASE}/pautadores/google-ads/analysis/zombie-keywords`,
    analysisVampireCampaigns: `${BASE}/pautadores/google-ads/analysis/vampire-campaigns`,
    analysisConsolidatedActionPlan: `${BASE}/pautadores/google-ads/analysis/consolidated-action-plan`,
    // Phase 12: Benchmark Cross-Account
    analysisAccountBenchmark: `${BASE}/pautadores/google-ads/analysis/account-benchmark`,
    analysisPortfolioRecommendation: `${BASE}/pautadores/google-ads/analysis/portfolio-recommendation`,
    analysisAccountPatterns: `${BASE}/pautadores/google-ads/analysis/account-patterns`,
    // Wave 4: Landing Pages, Funnel, Month Comparison
    analysisLandingPages: `${BASE}/pautadores/google-ads/analysis/landing-pages`,
    analysisConversionFunnel: `${BASE}/pautadores/google-ads/analysis/conversion-funnel`,
    analysisMonthComparison: `${BASE}/pautadores/google-ads/analysis/month-comparison`,
    // Wave 5A: Asset Analysis
    analysisAssetSummary: `${BASE}/pautadores/google-ads/analysis/asset-summary`,
    analysisAssetHeadlines: `${BASE}/pautadores/google-ads/analysis/asset-headlines`,
    analysisAssetDescriptions: `${BASE}/pautadores/google-ads/analysis/asset-descriptions`,
    analysisAssetSitelinks: `${BASE}/pautadores/google-ads/analysis/asset-sitelinks`,
    // Geography
    analysisGeo: `${BASE}/pautadores/google-ads/analysis/geo`,
    analysisGeoMap: `${BASE}/pautadores/google-ads/analysis/geo-map`,
    analysisCountryEfficiency: `${BASE}/pautadores/google-ads/analysis/country-efficiency`,
    analysisGeoTier: `${BASE}/pautadores/google-ads/analysis/geo-tier`,
    analysisLocations: `${BASE}/pautadores/google-ads/analysis/locations`,
    myAccounts: `${BASE}/pautadores/google-ads/my-accounts`,
  },
  alerts: {
    list: `${BASE}/alerts`,
    summary: `${BASE}/alerts/summary`,
    trend: `${BASE}/alerts/trend`,
    topAlerted: `${BASE}/alerts/top-alerted`,
    ranking: `${BASE}/alerts/ranking`,
    adsComparison: `${BASE}/alerts/ads-comparison`,
    thresholds: `${BASE}/alerts/thresholds`,
  },
  scheduledReports: {
    list: `${BASE}/pautadores/scheduled-reports`,
    create: `${BASE}/pautadores/scheduled-reports`,
    update: (id: number) => `${BASE}/pautadores/scheduled-reports/${id}`,
    delete: (id: number) => `${BASE}/pautadores/scheduled-reports/${id}`,
  },
};
