import { environment } from '../../../environments/environment';

const BASE = environment.apiUrl;

export const API_URLS = {
  auth: {
    login: `${BASE}/auth/login`,
    refresh: `${BASE}/auth/refresh`,
    logout: `${BASE}/auth/logout`,
    me: `${BASE}/auth/me`,
    changePassword: `${BASE}/auth/change-password`,
  },
  admin: {
    users: `${BASE}/admin/users`,
    campaigns: `${BASE}/admin/campaigns`,
    countries: `${BASE}/admin/countries`,
    roles: `${BASE}/admin/roles`,
    auditLog: `${BASE}/admin/audit-log`,
    stats: `${BASE}/admin/stats`,
    rechargesDashboard: `${BASE}/admin/recharges-dashboard`,
    conglomeradoEntries: `${BASE}/admin/conglomerado-entries`,
    pautadorAccounts: (id: number) => `${BASE}/admin/users/${id}/google-ads-accounts`,
    allGoogleAdsAccounts: `${BASE}/admin/users/google-ads-accounts`,
  },
  conglomerado: {
    entryToday: `${BASE}/conglomerado/entry/today`,
    entry: `${BASE}/conglomerado/entry`,
    entries: `${BASE}/conglomerado/entries`,
    weeklySummary: `${BASE}/conglomerado/weekly-summary`,
  },
  pautadores: {
    entriesDaily: `${BASE}/pautadores/entries/daily`,
    entriesWeekly: `${BASE}/pautadores/entries/weekly`,
    entriesWeeklyCalendar: `${BASE}/pautadores/entries/weekly-calendar`,
    consolidated: `${BASE}/pautadores/consolidated`,
    campaigns: `${BASE}/pautadores/campaigns`,
    dashboardKpis: `${BASE}/pautadores/dashboard/kpis`,
    dashboardCharts: `${BASE}/pautadores/dashboard/charts`,
    exportExcel: `${BASE}/pautadores/export/excel`,
    exportPdf: `${BASE}/pautadores/export/pdf`,
    conglomeradoContrast: `${BASE}/pautadores/conglomerado-contrast`,
  },
  gestion: {
    dashboardKpis: `${BASE}/gestion/dashboard/kpis`,
    reportsEffectiveness: `${BASE}/gestion/reports/effectiveness`,
    reportsConversions: `${BASE}/gestion/reports/conversions`,
    reportsByCountry: `${BASE}/gestion/reports/by-country`,
    reportsByWeek: `${BASE}/gestion/reports/by-week`,
    exportExcel: `${BASE}/gestion/export/excel`,
    exportPdf: `${BASE}/gestion/export/pdf`,
    rotations: `${BASE}/gestion/rotations`,
    rotationsAvailableUsers: `${BASE}/gestion/rotations/available-users`,
    rotationsCampaigns: `${BASE}/gestion/rotations/campaigns`,
    conglomeradoUsers: `${BASE}/gestion/conglomerado-users`,
    soporteImages: `${BASE}/gestion/soporte-images`,
  },
  system: {
    countries: `${BASE}/system/countries`,
    health: `${BASE}/system/health`,
  },
  googleAds: {
    campaigns: `${BASE}/pautadores/google-ads/campaigns`,
    campaignsByAccount: `${BASE}/pautadores/google-ads/campaigns-by-account`,
    campaignHistory: `${BASE}/pautadores/google-ads/campaigns`,
    billingAccounts: `${BASE}/pautadores/google-ads/billing/accounts`,
    billingHistory: `${BASE}/pautadores/google-ads/billing/history`,
    accountCharges: `${BASE}/pautadores/google-ads/billing/charges`,
    recharges: `${BASE}/pautadores/google-ads/billing/recharges`,
    rechargesExport: `${BASE}/pautadores/google-ads/billing/recharges/export`,
    sync: `${BASE}/pautadores/google-ads/sync`,
    analysisSpendingTrend: `${BASE}/pautadores/google-ads/analysis/spending-trend`,
    analysisDataRange: `${BASE}/pautadores/google-ads/analysis/data-range`,
    analysisPerformance: `${BASE}/pautadores/google-ads/analysis/performance`,
    analysisRankings: `${BASE}/pautadores/google-ads/analysis/rankings`,
    analysisBudgetDistribution: `${BASE}/pautadores/google-ads/analysis/budget-distribution`,
    myAccounts: `${BASE}/pautadores/google-ads/my-accounts`,
  },
  alerts: {
    list: `${BASE}/alerts`,
    summary: `${BASE}/alerts/summary`,
    trend: `${BASE}/alerts/trend`,
    topAlerted: `${BASE}/alerts/top-alerted`,
    ranking: `${BASE}/alerts/ranking`,
    adsComparison: `${BASE}/alerts/ads-comparison`,
    thresholds: `${BASE}/alerts/thresholds`,
  },
};
