-- Admin user: admin / admin123 (password should be changed after first login)
-- Password hash for 'admin123' with bcrypt 12 rounds
-- This hash will be generated by the seed script in TypeScript
-- Placeholder: will be replaced by migrate.ts
INSERT INTO users (username, email, password_hash, full_name, role_id, is_active)
SELECT 'admin', 'admin@pautas.com', '$ADMIN_HASH$', 'Administrador', r.id, TRUE
FROM roles r WHERE r.name = 'admin'
ON CONFLICT (username) DO NOTHING;
